apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-stable
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot
      track: stable
  template:
    metadata:
      labels:
        app: springboot
        track: stable
    spec:
      containers:
        - name: springboot
          image: ajaykhandare69docker/springboot-ci-cd-demo:latest
          ports:
            - containerPort: 8080
