apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      version: blue
  template:
    metadata:
      labels:
        app: springboot
        version: blue
    spec:
      containers:
        - name: springboot
          image: ajaykhandare69docker/springboot-ci-cd-demo:latest
          ports:
            - containerPort: 8080
