apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      track: canary
  template:
    metadata:
      labels:
        app: springboot
        track: canary
    spec:
      containers:
        - name: springboot
          image: springboot-app:green
          ports:
            - containerPort: 8080
